/*
 * AP_ParamIntegrity.cpp — Runtime parameter integrity verification
 *
 * See AP_ParamIntegrity.h for design documentation.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option)
 * any later version.
 */

#include "AP_ParamIntegrity.h"

#include <AP_HAL/AP_HAL.h>
#include <GCS_MAVLink/GCS.h>

#include <stdio.h>
#include <string.h>
#include <math.h>

extern const AP_HAL::HAL &hal;

// =============================================================================
//  WHITELIST
//
//  List every parameter name whose live value must be covered by the checksum.
//
//  Rules:
//    • Keep entries in strict ASCII-ascending (strcmp) order — uppercase A–Z,
//      digits, underscores only.  The offline generator sorts identically.
//    • After any edit here, re-run param_checksum_gen.py and paste the new
//      32-byte array into _reference_checksum[] below.
//    • Parameter names not present in a given firmware build cause check()
//      to return false immediately (hard failure — see missing-param policy
//      in AP_ParamIntegrity.h).
// =============================================================================

const char * const AP_ParamIntegrity::_whitelist[] = {
    // -----------------------------------------------------------------
    // Example entries — replace with your deployment's critical params.
    // Sorted: AVOID_ENABLE < FENCE_ENABLE < FS_EKF_ACTION < FS_THR_ENABLE
    // -----------------------------------------------------------------
    "AVOID_ENABLE",
    "FENCE_ENABLE",
    "FS_EKF_ACTION",
    "FS_THR_ENABLE",
};

const uint16_t AP_ParamIntegrity::_whitelist_count =
    sizeof(AP_ParamIntegrity::_whitelist) /
    sizeof(AP_ParamIntegrity::_whitelist[0]);


// =============================================================================
//  REFERENCE CHECKSUM
//
//  Generated by:
//    python3 Tools/scripts/param_checksum_gen.py  params/critical.param
//
//  The tool prints:
//    Canonical input:
//      AVOID_ENABLE=1
//      FENCE_ENABLE=1
//      FS_EKF_ACTION=1
//      FS_THR_ENABLE=1
//    SHA-256: e3b0c44298fc1c149afb ... (hex)
//    C array:
//      { 0xe3, 0xb0, ... }
//
//  Paste that C array below.
//
//  *** PLACEHOLDER (all-zero) — replace before deployment ***
//  A firmware built with this placeholder will always block arming when
//  ARMING_CHECK includes parameters.  This is intentional: it forces the
//  operator to embed a real checksum before the vehicle can be armed.
// =============================================================================

// const uint8_t AP_ParamIntegrity::_reference_checksum[AP_ParamIntegrity::SHA256_DIGEST_SIZE] = {
//     // Bytes 0–7
//     0x00, 0x00, 0x00, 0x00,  0x00, 0x00, 0x00, 0x00,
//     // Bytes 8–15
//     0x00, 0x00, 0x00, 0x00,  0x00, 0x00, 0x00, 0x00,
//     // Bytes 16–23
//     0x00, 0x00, 0x00, 0x00,  0x00, 0x00, 0x00, 0x00,
//     // Bytes 24–31
//     0x00, 0x00, 0x00, 0x00,  0x00, 0x00, 0x00, 0x00,
// };

const uint8_t AP_ParamIntegrity::_reference_checksum[AP_ParamIntegrity::SHA256_DIGEST_SIZE] = {
    0x02, 0xE9, 0x6C, 0xEC,
    0x17, 0x51, 0xF5, 0xD3,
    0x61, 0x8D, 0xF6, 0x0F,
    0x76, 0x42, 0x35, 0xE4,
    0x1F, 0xD1, 0x8C, 0x90,
    0xBA, 0xDE, 0x6C, 0xB5,
    0xBB, 0x1C, 0xA8, 0x12,
    0x1C, 0x44, 0x67, 0x3C
};

// =============================================================================
//  SHA-256  (self-contained FIPS 180-4 implementation)
//
//  No external crypto library dependency.  All state lives on the caller's
//  stack (SHA256_CTX ≈ 105 bytes; message schedule w[64] ≈ 256 bytes).
//  Macros are prefixed SHA256_ and #undef'd at end of section to avoid
//  polluting any translation unit that later includes this file's object.
// =============================================================================

// FIPS 180-4 §4.2.2 — SHA-256 round constants
static const uint32_t SHA256_K[64] = {
    0x428a2f98UL, 0x71374491UL, 0xb5c0fbcfUL, 0xe9b5dba5UL,
    0x3956c25bUL, 0x59f111f1UL, 0x923f82a4UL, 0xab1c5ed5UL,
    0xd807aa98UL, 0x12835b01UL, 0x243185beUL, 0x550c7dc3UL,
    0x72be5d74UL, 0x80deb1feUL, 0x9bdc06a7UL, 0xc19bf174UL,
    0xe49b69c1UL, 0xefbe4786UL, 0x0fc19dc6UL, 0x240ca1ccUL,
    0x2de92c6fUL, 0x4a7484aaUL, 0x5cb0a9dcUL, 0x76f988daUL,
    0x983e5152UL, 0xa831c66dUL, 0xb00327c8UL, 0xbf597fc7UL,
    0xc6e00bf3UL, 0xd5a79147UL, 0x06ca6351UL, 0x14292967UL,
    0x27b70a85UL, 0x2e1b2138UL, 0x4d2c6dfcUL, 0x53380d13UL,
    0x650a7354UL, 0x766a0abbUL, 0x81c2c92eUL, 0x92722c85UL,
    0xa2bfe8a1UL, 0xa81a664bUL, 0xc24b8b70UL, 0xc76c51a3UL,
    0xd192e819UL, 0xd6990624UL, 0xf40e3585UL, 0x106aa070UL,
    0x19a4c116UL, 0x1e376c08UL, 0x2748774cUL, 0x34b0bcb5UL,
    0x391c0cb3UL, 0x4ed8aa4aUL, 0x5b9cca4fUL, 0x682e6ff3UL,
    0x748f82eeUL, 0x78a5636fUL, 0x84c87814UL, 0x8cc70208UL,
    0x90befffaUL, 0xa4506cebUL, 0xbef9a3f7UL, 0xc67178f2UL,
};

// SHA-256 bit-operation macros (FIPS 180-4 §4.1.2)
#define SHA256_ROTR(x, n)   (((x) >> (n)) | ((x) << (32u - (n))))
#define SHA256_CH(x, y, z)  (((x) & (y)) ^ (~(x) & (z)))
#define SHA256_MAJ(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define SHA256_EP0(x)  (SHA256_ROTR(x,  2) ^ SHA256_ROTR(x, 13) ^ SHA256_ROTR(x, 22))
#define SHA256_EP1(x)  (SHA256_ROTR(x,  6) ^ SHA256_ROTR(x, 11) ^ SHA256_ROTR(x, 25))
#define SHA256_SIG0(x) (SHA256_ROTR(x,  7) ^ SHA256_ROTR(x, 18) ^ ((x) >>  3))
#define SHA256_SIG1(x) (SHA256_ROTR(x, 17) ^ SHA256_ROTR(x, 19) ^ ((x) >> 10))

// FIPS 180-4 §5.3.3 — SHA-256 initial hash value (first 32 bits of
// the fractional parts of the square roots of the first eight primes)
void AP_ParamIntegrity::sha256_init(SHA256_CTX &ctx)
{
    ctx.state[0] = 0x6a09e667UL;
    ctx.state[1] = 0xbb67ae85UL;
    ctx.state[2] = 0x3c6ef372UL;
    ctx.state[3] = 0xa54ff53aUL;
    ctx.state[4] = 0x510e527fUL;
    ctx.state[5] = 0x9b05688cUL;
    ctx.state[6] = 0x1f83d9abUL;
    ctx.state[7] = 0x5be0cd19UL;
    ctx.bit_count = 0;
    ctx.buf_len   = 0;
}

// FIPS 180-4 §6.2.2 — SHA-256 hash computation (one 512-bit block)
void AP_ParamIntegrity::sha256_transform(SHA256_CTX         &ctx,
                                          const uint8_t block[SHA256_BLOCK_SIZE])
{
    // Message schedule W[0..63]
    uint32_t w[64];
    for (uint8_t i = 0; i < 16; i++) {
        w[i] =   ((uint32_t)block[i * 4    ] << 24)
               | ((uint32_t)block[i * 4 + 1] << 16)
               | ((uint32_t)block[i * 4 + 2] <<  8)
               | ((uint32_t)block[i * 4 + 3]);
    }
    for (uint8_t i = 16; i < 64; i++) {
        w[i] = SHA256_SIG1(w[i - 2]) + w[i - 7]
             + SHA256_SIG0(w[i - 15]) + w[i - 16];
    }

    // Working variables initialised from current hash state
    uint32_t a = ctx.state[0], b = ctx.state[1],
             c = ctx.state[2], d = ctx.state[3],
             e = ctx.state[4], f = ctx.state[5],
             g = ctx.state[6], h = ctx.state[7];

    // 64 rounds
    for (uint8_t i = 0; i < 64; i++) {
        const uint32_t t1 = h + SHA256_EP1(e) + SHA256_CH(e, f, g)
                            + SHA256_K[i] + w[i];
        const uint32_t t2 = SHA256_EP0(a) + SHA256_MAJ(a, b, c);
        h = g; g = f; f = e; e = d + t1;
        d = c; c = b; b = a; a = t1 + t2;
    }

    // Add the compressed chunk to the current hash value
    ctx.state[0] += a; ctx.state[1] += b;
    ctx.state[2] += c; ctx.state[3] += d;
    ctx.state[4] += e; ctx.state[5] += f;
    ctx.state[6] += g; ctx.state[7] += h;
}

void AP_ParamIntegrity::sha256_update(SHA256_CTX   &ctx,
                                       const uint8_t *data,
                                       size_t         len)
{
    for (size_t i = 0; i < len; i++) {
        ctx.buf[ctx.buf_len++] = data[i];
        ctx.bit_count += 8;          // count bits as we go; includes buffered bytes
        if (ctx.buf_len == SHA256_BLOCK_SIZE) {
            sha256_transform(ctx, ctx.buf);
            ctx.buf_len = 0;
        }
    }
}

// FIPS 180-4 §5.1.1 — padding and length encoding
void AP_ParamIntegrity::sha256_final(SHA256_CTX &ctx,
                                      uint8_t digest[SHA256_DIGEST_SIZE])
{
    // bit_count already covers all bytes including those still in buf.
    const uint64_t total_bits = ctx.bit_count;
    uint8_t i = ctx.buf_len;

    // Append the mandatory 0x80 padding byte
    ctx.buf[i++] = 0x80;

    // If insufficient room for the 8-byte length field, flush the block
    if (i > 56) {
        while (i < SHA256_BLOCK_SIZE) {
            ctx.buf[i++] = 0x00;
        }
        sha256_transform(ctx, ctx.buf);
        i = 0;
    }

    // Zero-pad up to byte 56
    while (i < 56) {
        ctx.buf[i++] = 0x00;
    }

    // Append message length as big-endian 64-bit integer (bytes 56–63)
    ctx.buf[56] = (uint8_t)(total_bits >> 56);
    ctx.buf[57] = (uint8_t)(total_bits >> 48);
    ctx.buf[58] = (uint8_t)(total_bits >> 40);
    ctx.buf[59] = (uint8_t)(total_bits >> 32);
    ctx.buf[60] = (uint8_t)(total_bits >> 24);
    ctx.buf[61] = (uint8_t)(total_bits >> 16);
    ctx.buf[62] = (uint8_t)(total_bits >>  8);
    ctx.buf[63] = (uint8_t)(total_bits      );
    sha256_transform(ctx, ctx.buf);

    // Serialise the eight 32-bit state words to digest[] (big-endian)
    for (uint8_t k = 0; k < 8; k++) {
        digest[k * 4    ] = (uint8_t)(ctx.state[k] >> 24);
        digest[k * 4 + 1] = (uint8_t)(ctx.state[k] >> 16);
        digest[k * 4 + 2] = (uint8_t)(ctx.state[k] >>  8);
        digest[k * 4 + 3] = (uint8_t)(ctx.state[k]      );
    }
}

// Clean up file-scoped macros to avoid leaking into other TUs via unity builds
#undef SHA256_ROTR
#undef SHA256_CH
#undef SHA256_MAJ
#undef SHA256_EP0
#undef SHA256_EP1
#undef SHA256_SIG0
#undef SHA256_SIG1


// =============================================================================
//  CANONICAL SERIALISATION
// =============================================================================

/*
 * format_entry — produce one line of canonical output.
 *
 * Formatting contract (must be byte-for-byte identical to Python generator):
 *
 *   Integer types (INT8/16/32):  "%s=%d\n"
 *   Float, fractional part < 1e-6:  "%s=%d\n"   (whole number, no '.')
 *   Float, fractional part ≥ 1e-6:  "%s=%.6f\n" (always 6 decimal places)
 *
 * AP_PARAM_INT32: cast to int (32-bit on all ArduPilot Cortex targets).
 * AP_PARAM_FLOAT: modff() splits the value; fabsf(frac) guards -0.0 and
 *   tiny rounding errors in IEEE 754 representation of exact integers.
 *
 * Returns bytes written (> 0), or -1 on truncation / unsupported type.
 */
int AP_ParamIntegrity::format_entry(const char *name,
                                     AP_Param   *param,
                                     ap_var_type type,
                                     char       *out_buf,
                                     size_t      buf_size)
{
    int len;

    switch (type) {

    case AP_PARAM_INT8:
        len = snprintf(out_buf, buf_size, "%s=%d\n",
                       name, (int)((AP_Int8 *)param)->get());
        break;

    case AP_PARAM_INT16:
        len = snprintf(out_buf, buf_size, "%s=%d\n",
                       name, (int)((AP_Int16 *)param)->get());
        break;

    case AP_PARAM_INT32:
        // int == int32_t on ARM Cortex-M and SITL x86_64 (LP64 model).
        len = snprintf(out_buf, buf_size, "%s=%d\n",
                       name, (int)((AP_Int32 *)param)->get());
        break;

    case AP_PARAM_FLOAT: {
        const float value = ((AP_Float *)param)->get();
        float int_part;
        const float frac = modff(value, &int_part);
        if (fabsf(frac) < 1e-6f) {
            // Whole-number float → integer representation
            len = snprintf(out_buf, buf_size, "%s=%d\n",
                           name, (int)int_part);
        } else {
            // Fractional float → 6 decimal places
            // Cast to double: snprintf on some bare-metal libc variants
            // treats %f as double; the explicit cast avoids UB and ensures
            // the Python tool and firmware produce the same digit string.
            len = snprintf(out_buf, buf_size, "%s=%.6f\n",
                           name, (double)value);
        }
        break;
    }

    default:
        // AP_PARAM_VECTOR3F, AP_PARAM_GROUP, AP_PARAM_NONE — not supported.
        // If a whitelisted param resolves to one of these types, check()
        // returns false with a format-error message.
        return -1;
    }

    // snprintf returns the number of characters that *would* have been
    // written; if >= buf_size the output was truncated.
    if (len <= 0 || (size_t)len >= buf_size) {
        return -1;
    }
    return len;
}


// =============================================================================
//  PUBLIC INTERFACE
// =============================================================================

bool AP_ParamIntegrity::check(bool display_failure) const
{
    SHA256_CTX ctx;
    sha256_init(ctx);

    // Sizing: longest AP_Param name = 16 chars, '=' = 1, longest value:
    //   integer  → "-2147483648"  = 11 chars
    //   %.6f     → "-3276800.000000" ≈ 16 chars (practical range for params)
    // Add '\n' + NUL + headroom → 48 bytes is sufficient.
    char entry_buf[48];

    for (uint16_t i = 0; i < _whitelist_count; i++) {
        const char *param_name = _whitelist[i];

        ap_var_type type;
        AP_Param *param = AP_Param::find(param_name, &type);

        if (param == nullptr) {
            // Hard failure: whitelisted parameter not registered in this
            // firmware build.  Could indicate version mismatch or a stale
            // whitelist.  A specific message is more actionable than the
            // generic "Param checksum mismatch" from the caller.
            if (display_failure) {
                GCS_SEND_TEXT(MAV_SEVERITY_CRITICAL,
                              "ParamIntegrity: %s not found", param_name);
            }
            return false;
        }

        const int len = format_entry(param_name, param, type,
                                     entry_buf, sizeof(entry_buf));
        if (len < 0) {
            // Unsupported type or buffer too small.
            if (display_failure) {
                GCS_SEND_TEXT(MAV_SEVERITY_CRITICAL,
                              "ParamIntegrity: format error for %s", param_name);
            }
            return false;
        }

        sha256_update(ctx, reinterpret_cast<const uint8_t *>(entry_buf),
                      static_cast<size_t>(len));
    }

    uint8_t computed[SHA256_DIGEST_SIZE];
    sha256_final(ctx, computed);

    // DEBUG HASH PRINT
    if (display_failure) {
        char computed_hex[65];
        char stored_hex[65];

        for (uint8_t i = 0; i < SHA256_DIGEST_SIZE; i++) {
            snprintf(&computed_hex[i * 2], 3, "%02X", computed[i]);
            snprintf(&stored_hex[i * 2], 3, "%02X", _reference_checksum[i]);
        }

        computed_hex[64] = '\0';
        stored_hex[64] = '\0';

        // Computed checksum
        GCS_SEND_TEXT(MAV_SEVERITY_INFO,
                    "CMP-1: %.30s", computed_hex);
        GCS_SEND_TEXT(MAV_SEVERITY_INFO,
                    "CMP-2: %.30s", &computed_hex[30]);
        GCS_SEND_TEXT(MAV_SEVERITY_INFO,
                    "CMP-3: %.4s", &computed_hex[60]);

        // Stored/reference checksum
        GCS_SEND_TEXT(MAV_SEVERITY_INFO,
                    "REF-1: %.30s", stored_hex);
        GCS_SEND_TEXT(MAV_SEVERITY_INFO,
                    "REF-2: %.30s", &stored_hex[30]);
        GCS_SEND_TEXT(MAV_SEVERITY_INFO,
                    "REF-3: %.4s", &stored_hex[60]);
    }


    // Constant-time comparison: accumulate XOR differences so the loop
    // runs for a fixed number of iterations regardless of where a mismatch
    // occurs.  Prevents timing-based side-channel leak of the reference hash.
    uint8_t diff = 0;
    for (uint8_t i = 0; i < SHA256_DIGEST_SIZE; i++) {
        diff |= computed[i] ^ _reference_checksum[i];
    }



    // The caller (AP_Arming_Copter::parameter_checks) already emits the
    // user-visible "Param checksum mismatch" message via check_failed(), so
    // we do not duplicate it here.
    return (diff == 0);
}